---

# This keeps ansible from complaining if no other variables are defined
dummy:

#
# Kludge for JHU/NWU monitor swap
#
ceph_monitor_hosts: "{{ ['nwu-mon1', 'nwu-mon2', 'jhu-mon3'] }}"
ceph_monitor_addrs: "{{ ['172.16.2.11', '172.16.2.12', '172.16.1.13'] }}"
