---
- name: Check for local copy of radosgw keyring
  local_action: stat path={{ playbook_dir }}/state/ceph.client.radosgw.keyring
  register: local_key
  become: no

- name: Generate a radosgw keyring
  shell: "ceph-authtool --create-keyring {{ radosgw_key_path }} --gen-key -n client.radosgw.gateway --cap osd 'allow rwx' --cap mon 'allow rwx'"
  args:
    creates: "{{ radosgw_key_path }}"
  when: local_key.stat.exists == False

- name: Set ownership on radosgw keyring
  file:
    path: "{{ radosgw_key_path }}"
    owner: ceph
    group: ceph
    mode: 0600
  when: local_key.stat.exists == False

- name: Import the keyring into Ceph
  shell: "ceph -k {{ admin_key_path }} auth add client.radosgw.gateway -i {{ radosgw_key_path }}"
  when: local_key.stat.exists == False

- name: Save the new radosgw keyring
  fetch:
    src: "{{ radosgw_key_path }}"
    dest: "{{ playbook_dir }}/state/"
    flat: yes
  when: local_key.stat.exists == False


