---
- name: Check for local copy of radosgw keyring
  local_action: stat path={{ playbook_dir }}/state/ceph.client.radosgw.keyring
  register: local_key
  become: no

- name: Fail if local copy does not exist
  fail: msg="ceph.client.radosgw.keyring keyring is expected to exist!"
  when: local_key.stat.exists == False

- name: Copy over radosgw keyring
  copy:
    src: "{{ playbook_dir }}/state/ceph.client.radosgw.keyring"
    dest: "{{ radosgw_key_path }}"
    owner: ceph
    group: ceph
    mode: 0600

